print("winter is coming")
print("you know nothing","Ahed Bahri")
#Elton John - Your Song
print ("It's a little bit funny this feeling inside")
print ("I'm not one of those who can easily hide, I")
print ("Don't have much money but boy if I did")
print ("I'd buy a big house where we both could live")
print(" ")
print ("If I was a sculptor, but then again no")
print ("Or a man who makes potions in a traveling show")
print ("Oh I know it's not much but it's the best I can do")
print ("My gift is my song")
print ("And this one's for you")
print(" ")
print ("And you can tell everybody this is your song")
print ("It may be quite simple but now that it's done")
print ("I hope you don't mind")
print ("I hope you don't mind")
print ("That I put down in words")
print ("How wonderful life is while you're in the world")
print(" ")
print ("I sat on the roof and kicked off the moss")
print ("Well a few of the verses well they've got me quite cross")
print (" the sun's been quite kind")
print (" I wrote this song")
print ("It's for people like you that")
print ("Keep it turned on")
print(" ")
print ("So excuse me forgetting")
print ("But these things I do")
print ("You see I've forgotten")
print ("If they're green or they're blue")
print ("Anyway, the thing is, what I really mean")
print ("Yours are the sweetest eyes I've ever seen")
print(" ")
print ("And you can tell everybody this is your song")
print ("It may be quite simple but")
print ("Now that it's done")
print ("I hope you don't mind")
print ("I hope you don't mind")
print ("That I put down in words")
print ("How wonderful life is while you're in the world")
print ("I hope you don't mind")
print ("I hope you don't mind")
print ("That I put down in words")
print ("How wonderful life is while you're in the world")